app/views.py
from flask import render_template, Blueprint

main_blueprint = Blueprint('main', __name__)


@main_blueprint.route('/')
def index():
    return render_template('index.html')

app/templates/_macros.html
<!-- Put your reusable template code into macros here -->

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>{{ config.APP_NAME }}</title>
  <!-- meta -->
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  {% block meta %}{% endblock %}
  <!-- styles -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet" media="screen">
  {% block links %}{% endblock %}
</head>

<body>
  <!-- Header -->
  <header>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
      <div class="container">
        <!-- Navbar Brand -->
        <a class="navbar-brand" href="{{ url_for('main.index') }}">{{ config.APP_NAME }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
	          <div class="dropdown-divider"></div>
        <div class="collapse navbar-collapse" id="navbarNav">
          <!-- Main Navigation -->
          <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
	    {% if session['is_superadmin'] == True %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.list_users') }}">Manage Users</a>
            </li>
	    {%endif%}
            <li class="nav-item">
		    <a class="nav-link" href="{{ url_for('sitekost.list_sites') }}">Manage Sites</a>
            </li>
            <li class="nav-item">
		    <a class="nav-link" href="{{ url_for('sitekost.list_pakets') }}">Manage Paket Inet</a>
            </li>
            <li class="nav-item">
		    <a class="nav-link" href="{{ url_for('sitekost.list_hslogins') }}">Manage Hotspot Logins</a>
            </li>
	    {% endif %}
          </ul>
          <!-- Login/Logout -->
          <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="userActions" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">{{current_user.username | capitalize}}</a>
              <div class="dropdown-menu" aria-labelledby="userActions">
                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <!-- Flash Messages -->
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  <div class="alert alert-{{ category }} alert-dismisible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}
  <!-- Main Content -->
  {% block content %}{% endblock %}
  <!-- Footer-->
  <footer>
    <div class="container-fluid bg-light py-5">
      <!-- Copyrights -->
      <div class="text-center">
        <p class="text-muted mb-0 py-2">&copy;2020 {{ config.APP_NAME }} | All rights reserved.</p>
      </div>
    </div>
  </footer>
  <!-- scripts -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="{{ url_for('static', filename='main.js') }}" type="text/javascript"></script>
  {% block scripts %}{% endblock %}
</body>

</html>

app/templates/error.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron my-4">
  <div class="text-center">
    <h1>{{ '%s - %s' % (error.code, error.name) }}</h1>
    <p>{{ error.description }}.</p>
  </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>Welcome!</h1>
  <hr>
  <p>Add some content here!</p>
</div>
{% endblock %}